import Vue from "vue";
import chronometer from './chronometer.vue';
import richMessage from './richMessage.vue';
import toolbar from './toolbar.vue';
import snackbar from './snackbar.vue';
import drawer from './drawer.vue';
Vue.component('chronometer', chronometer);
Vue.component('richMessage', richMessage);
Vue.component('toolbar', toolbar);
Vue.component('snackbar', snackbar);
Vue.component('drawer', drawer);